class VirtualMachine:
    def __init__(self, ast):
        self.ast = ast
        self.variables = {}
        self.scenes = {}
        self.current_scene = None

    def setup(self):
        # Initialize variables and map out scenes
        for node in self.ast['body']:
            if node['type'] == 'VarDeclaration':
                self.variables[node['name']] = node['value']
            elif node['type'] == 'SceneNode':
                self.scenes[node['name']] = node
        
        # Set initial state
        if 'start' in self.scenes:
            self.current_scene = 'start'
        elif self.scenes:
            self.current_scene = list(self.scenes.keys())[0]

    def eval_condition(self, condition_str):
        # Break down the string "var_name == value" generated by the parser
        parts = condition_str.split('==')
        if len(parts) == 2:
            var_name = parts[0].strip()
            target_val = parts[1].strip()
            # Compare as strings to avoid type-casting issues
            current_val = str(self.variables.get(var_name, "")).lower()
            return current_val == target_val.lower()
        return False

    def run(self):
        self.setup()
        if not self.current_scene:
            print("VM Error: No scenes to run.")
            return

        print("\n" + "="*40)
        print(" 🎮 LAUNCHING QUESTSCRIPT ENGINE 🎮")
        print("="*40 + "\n")

        # The Main Game Loop
        while self.current_scene:
            scene = self.scenes.get(self.current_scene)
            if not scene:
                print(f"VM Crash: Scene '{self.current_scene}' vanished.")
                break
            
            next_scene = self.execute_statements(scene['statements'])
            
            if next_scene == 'END_GAME':
                break
            elif next_scene:
                self.current_scene = next_scene
            else:
                # If a scene finishes without a jump or choices, it halts smoothly.
                break
                
        print("\n" + "="*40)
        print(" 🛑 GAME OVER 🛑")
        print("="*40 + "\n")

    def execute_statements(self, statements):
        choices = []
        
        for stmt in statements:
            if stmt['type'] == 'PrintNode':
                # The lexer already strips quotes, so we just print the args
                text = " ".join(stmt['args'])
                print(text)
            
            elif stmt['type'] == 'SetNode':
                self.variables[stmt['variable']] = stmt['new_value']
            
            elif stmt['type'] == 'GotoNode':
                return stmt['target']
            
            elif stmt['type'] == 'ChoiceNode':
                choices.append(stmt)
            
            elif stmt['type'] == 'EndNode':
                return 'END_GAME'
                
            elif stmt['type'] == 'IfNode':
                # Evaluate nested blocks dynamically 
                if self.eval_condition(stmt['condition']):
                    res = self.execute_statements(stmt['if_body'])
                    if res: return res
                else:
                    res = self.execute_statements(stmt['else_body'])
                    if res: return res

        # If choices were collected, trigger the interactive prompt
        if choices:
            print() # Blank line for readability 
            for i, choice in enumerate(choices):
                print(f"  [{i+1}] {choice['text']}")
            
            while True:
                try:
                    raw = input("\nWhat do you do? > ")
                    print(raw)          # Echo choice — required when stdin is piped
                    print()             # Blank separator before next scene text
                    pick = int(raw)
                    if 1 <= pick <= len(choices):
                        return choices[pick-1]['target']
                    else:
                        print("Invalid choice. Please select an available number.")
                except ValueError:
                    print("Numbers only, please. Try again.")
        
        return None